version: '3'

services:
  api:
    container_name: apicolors
    restart: always
    build: .
    links:
      - 'db'
    ports:
      - '6969:3000'
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: tec
    depends_on:
      - db

  db:
    container_name: dbapicolors
    image: mariadb
    ports:
      - '3306:3306'
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: tec
    volumes:
      - './db:/bitnami/mariadb'
